//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Expression.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace TaxTest.ExpressionParsing {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IExpressionListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class ExpressionBaseListener : IExpressionListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] ExpressionParser.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] ExpressionParser.IdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.simple"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimple([NotNull] ExpressionParser.SimpleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.simple"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimple([NotNull] ExpressionParser.SimpleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] ExpressionParser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] ExpressionParser.TermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.unary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnary([NotNull] ExpressionParser.UnaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.unary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnary([NotNull] ExpressionParser.UnaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactor([NotNull] ExpressionParser.FactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactor([NotNull] ExpressionParser.FactorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.float_num"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFloat_num([NotNull] ExpressionParser.Float_numContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.float_num"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFloat_num([NotNull] ExpressionParser.Float_numContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.complete_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComplete_expression([NotNull] ExpressionParser.Complete_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.complete_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComplete_expression([NotNull] ExpressionParser.Complete_expressionContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace TaxTest.ExpressionParsing
